name: Quality

on:
  - push
  - pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: |
          pnpm lint:oxlint
          pnpm lint:eslint

      - name: Check formatting
        run: pnpm format
